apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: kubernetes
        kubernetes_sd_configs:
        - api_server: 'https://kubernetes'
          role: pod
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_name
          target_label: container_label_io_kubernetes_pod_name
        - source_labels:
          - __meta_kubernetes_namespace
          target_label: container_label_io_kubernetes_pod_namespace
        - source_labels:
          - __meta_kubernetes_pod_container_port_number
          target_label: container_label_port